---
modules:
  default:
    metrics:
    - name: sensor
      type: object
      path: "{ @ }"
      help: sensor and associated values 
      labels:
        broker_id: "{ $.broker_correlation_id }" 
        name: "{ $.timeseries[*].name }"
        luid: "{ $.l_uid }"         
      values:      
        puid: "{ $.p_uid }"                       
        value: "{ $.timeseries[*].value }" 